language: node_js
node_js:
  - "10"

build_service_job: &BUILD_SERVICE_JOB

  install:
    - travis_retry npm install
    - cd -

  script: travis_build.sh


jobs:
  include:
    - <<: *BUILD_SERVICE_JOB
      name: "Build Users API"
      if: type = push AND branch = master
